MERGE(Gluconobacteroxydans:MICROBE{name: 'Gluconobacter oxydans'})
MERGE(ammonium:CHEMICAL{name: 'ammonium'})
MERGE (Gluconobacteroxydans)-[:CONSUMES]->(ammonium)
MERGE(sevencyanosevendeazaguaninesynthaseQueC:ENZYME{name: '7-cyano-7-deazaguanine synthase QueC'})
MERGE (Gluconobacteroxydans)-[:SYNTHASIZES]->(sevencyanosevendeazaguaninesynthaseQueC)
MERGE (sevencyanosevendeazaguaninesynthaseQueC)-[:CATALYZES]->(ammonium)
MERGE(tRNAuridine5carboxymethylaminomethyl34synthesisGTPaseMnmE:ENZYME{name: 'tRNA uridine-5-carboxymethylaminomethyl(34) synthesis GTPase MnmE'})
MERGE (Gluconobacteroxydans)-[:SYNTHASIZES]->(tRNAuridine5carboxymethylaminomethyl34synthesisGTPaseMnmE)
MERGE (tRNAuridine5carboxymethylaminomethyl34synthesisGTPaseMnmE)-[:CATALYZES]->(ammonium)
MERGE(tRNAuridine5carboxymethylaminomethyl34synthesisenzymeMnmG:ENZYME{name: 'tRNA uridine-5-carboxymethylaminomethyl(34) synthesis enzyme MnmG'})
MERGE (Gluconobacteroxydans)-[:SYNTHASIZES]->(tRNAuridine5carboxymethylaminomethyl34synthesisenzymeMnmG)
MERGE (tRNAuridine5carboxymethylaminomethyl34synthesisenzymeMnmG)-[:CATALYZES]->(ammonium)
MERGE(ammoniumtransporter:ENZYME{name: 'ammonium transporter'})
MERGE (Gluconobacteroxydans)-[:SYNTHASIZES]->(ammoniumtransporter)
MERGE (ammoniumtransporter)-[:CATALYZES]->(ammonium)
MERGE(imidazoleglycerolphosphatesynthase:ENZYME{name: 'imidazole glycerol phosphate synthase'})
MERGE (Gluconobacteroxydans)-[:SYNTHASIZES]->(imidazoleglycerolphosphatesynthase)
MERGE (imidazoleglycerolphosphatesynthase)-[:CATALYZES]->(ammonium)
MERGE(AsptRNAAsnGlutRNAGlnamidotransferase:ENZYME{name: 'Asp-tRNA(Asn)/Glu-tRNA(Gln) amidotransferase'})
MERGE (Gluconobacteroxydans)-[:SYNTHASIZES]->(AsptRNAAsnGlutRNAGlnamidotransferase)
MERGE (AsptRNAAsnGlutRNAGlnamidotransferase)-[:CATALYZES]->(ammonium)
MERGE(nitritereductasesmallsubunitNirD:ENZYME{name: 'nitrite reductase small subunit NirD'})
MERGE (Gluconobacteroxydans)-[:SYNTHASIZES]->(nitritereductasesmallsubunitNirD)
MERGE (nitritereductasesmallsubunitNirD)-[:CATALYZES]->(ammonium)
MERGE(asparaginesynthaseglutaminehydrolyzing:ENZYME{name: 'asparagine synthase (glutamine-hydrolyzing)'})
MERGE (Gluconobacteroxydans)-[:SYNTHASIZES]->(asparaginesynthaseglutaminehydrolyzing)
MERGE (asparaginesynthaseglutaminehydrolyzing)-[:CATALYZES]->(ammonium)
MERGE(glutaminehydrolyzingGMPsynthase:ENZYME{name: 'glutamine-hydrolyzing GMP synthase'})
MERGE (Gluconobacteroxydans)-[:SYNTHASIZES]->(glutaminehydrolyzingGMPsynthase)
MERGE (glutaminehydrolyzingGMPsynthase)-[:CATALYZES]->(ammonium)
MERGE(NADsynthase:ENZYME{name: 'NAD(+) synthase'})
MERGE (Gluconobacteroxydans)-[:SYNTHASIZES]->(NADsynthase)
MERGE (NADsynthase)-[:CATALYZES]->(ammonium)
MERGE(typeIglutamateammonialigase:ENZYME{name: 'type I glutamate--ammonia ligase'})
MERGE (Gluconobacteroxydans)-[:SYNTHASIZES]->(typeIglutamateammonialigase)
MERGE (typeIglutamateammonialigase)-[:CATALYZES]->(ammonium)
MERGE(glutaminehydrolyzingcarbamoylphosphatesynthase:ENZYME{name: 'glutamine-hydrolyzing carbamoyl-phosphate synthase'})
MERGE (Gluconobacteroxydans)-[:SYNTHASIZES]->(glutaminehydrolyzingcarbamoylphosphatesynthase)
MERGE (glutaminehydrolyzingcarbamoylphosphatesynthase)-[:CATALYZES]->(ammonium)
MERGE(CTPsynthase:ENZYME{name: 'CTP synthase'})
MERGE (Gluconobacteroxydans)-[:SYNTHASIZES]->(CTPsynthase)
MERGE (CTPsynthase)-[:CATALYZES]->(ammonium)
MERGE (Gluconobacteroxydans)-[:PRODUCES]->(ammonium)
MERGE(Mg2:CHEMICAL{name: 'Mg2+'})
MERGE (Gluconobacteroxydans)-[:CONSUMES]->(Mg2)
MERGE(magnesiumtransporterCorAfamilyprotein:ENZYME{name: 'magnesium transporter CorA family protein'})
MERGE (Gluconobacteroxydans)-[:SYNTHASIZES]->(magnesiumtransporterCorAfamilyprotein)
MERGE (magnesiumtransporterCorAfamilyprotein)-[:CATALYZES]->(Mg2)
MERGE(Co2Mg2effluxproteinApaG:ENZYME{name: 'Co2+/Mg2+ efflux protein ApaG'})
MERGE (Gluconobacteroxydans)-[:SYNTHASIZES]->(Co2Mg2effluxproteinApaG)
MERGE (Co2Mg2effluxproteinApaG)-[:CATALYZES]->(Mg2)
MERGE(cationtransporter:ENZYME{name: 'cation transporter'})
MERGE (Gluconobacteroxydans)-[:SYNTHASIZES]->(cationtransporter)
MERGE (cationtransporter)-[:CATALYZES]->(Mg2)
MERGE(trimericintracellularcationchannelfamilyprotein:ENZYME{name: 'trimeric intracellular cation channel family protein'})
MERGE (Gluconobacteroxydans)-[:SYNTHASIZES]->(trimericintracellularcationchannelfamilyprotein)
MERGE (trimericintracellularcationchannelfamilyprotein)-[:CATALYZES]->(Mg2)
MERGE(NCS1familynucleobasecationsymporter1:ENZYME{name: 'NCS1 family nucleobase:cation symporter-1'})
MERGE (Gluconobacteroxydans)-[:SYNTHASIZES]->(NCS1familynucleobasecationsymporter1)
MERGE (NCS1familynucleobasecationsymporter1)-[:CATALYZES]->(Mg2)
MERGE(divalentmetalcationtransporter:ENZYME{name: 'divalent metal cation transporter'})
MERGE (Gluconobacteroxydans)-[:SYNTHASIZES]->(divalentmetalcationtransporter)
MERGE (divalentmetalcationtransporter)-[:CATALYZES]->(Mg2)
MERGE (Gluconobacteroxydans)-[:PRODUCES]->(Mg2)
MERGE(oxygen:CHEMICAL{name: 'oxygen'})
MERGE (Gluconobacteroxydans)-[:CONSUMES]->(oxygen)
MERGE(fivedemethoxyubiquinol8fivehydroxylaseUbiM:ENZYME{name: '5-demethoxyubiquinol-8 5-hydroxylase UbiM'})
MERGE (Gluconobacteroxydans)-[:SYNTHASIZES]->(fivedemethoxyubiquinol8fivehydroxylaseUbiM)
MERGE (fivedemethoxyubiquinol8fivehydroxylaseUbiM)-[:CATALYZES]->(oxygen)
MERGE(bacterioferritin:ENZYME{name: 'bacterioferritin'})
MERGE (Gluconobacteroxydans)-[:SYNTHASIZES]->(bacterioferritin)
MERGE (bacterioferritin)-[:CATALYZES]->(oxygen)
MERGE(protoporphyrinogenoxidaseHemJ:ENZYME{name: 'protoporphyrinogen oxidase HemJ'})
MERGE (Gluconobacteroxydans)-[:SYNTHASIZES]->(protoporphyrinogenoxidaseHemJ)
MERGE (protoporphyrinogenoxidaseHemJ)-[:CATALYZES]->(oxygen)
MERGE(pyrroloquinolinequinonesynthasePqqC:ENZYME{name: 'pyrroloquinoline-quinone synthase PqqC'})
MERGE (Gluconobacteroxydans)-[:SYNTHASIZES]->(pyrroloquinolinequinonesynthasePqqC)
MERGE (pyrroloquinolinequinonesynthasePqqC)-[:CATALYZES]->(oxygen)
MERGE(ubiquinoloxidasesubunitII:ENZYME{name: 'ubiquinol oxidase subunit II'})
MERGE (Gluconobacteroxydans)-[:SYNTHASIZES]->(ubiquinoloxidasesubunitII)
MERGE (ubiquinoloxidasesubunitII)-[:CATALYZES]->(oxygen)
MERGE(cytochromedubiquinoloxidasesubunitII:ENZYME{name: 'cytochrome d ubiquinol oxidase subunit II'})
MERGE (Gluconobacteroxydans)-[:SYNTHASIZES]->(cytochromedubiquinoloxidasesubunitII)
MERGE (cytochromedubiquinoloxidasesubunitII)-[:CATALYZES]->(oxygen)
MERGE(cytochromedubiquinoloxidase:ENZYME{name: 'cytochrome d ubiquinol oxidase'})
MERGE (Gluconobacteroxydans)-[:SYNTHASIZES]->(cytochromedubiquinoloxidase)
MERGE (cytochromedubiquinoloxidase)-[:CATALYZES]->(oxygen)
MERGE(cytochromeoubiquinoloxidase:ENZYME{name: 'cytochrome o ubiquinol oxidase'})
MERGE (Gluconobacteroxydans)-[:SYNTHASIZES]->(cytochromeoubiquinoloxidase)
MERGE (cytochromeoubiquinoloxidase)-[:CATALYZES]->(oxygen)
MERGE(cytochromeubiquinoloxidasesubunitI:ENZYME{name: 'cytochrome ubiquinol oxidase subunit I'})
MERGE (Gluconobacteroxydans)-[:SYNTHASIZES]->(cytochromeubiquinoloxidasesubunitI)
MERGE (cytochromeubiquinoloxidasesubunitI)-[:CATALYZES]->(oxygen)
MERGE(cysteinedioxygenasetypeI:ENZYME{name: 'cysteine dioxygenase type I'})
MERGE (Gluconobacteroxydans)-[:SYNTHASIZES]->(cysteinedioxygenasetypeI)
MERGE (cysteinedioxygenasetypeI)-[:CATALYZES]->(oxygen)
MERGE(FMNH2dependentalkanesulfonatemonooxygenase:ENZYME{name: 'FMNH2-dependent alkanesulfonate monooxygenase'})
MERGE (Gluconobacteroxydans)-[:SYNTHASIZES]->(FMNH2dependentalkanesulfonatemonooxygenase)
MERGE (FMNH2dependentalkanesulfonatemonooxygenase)-[:CATALYZES]->(oxygen)
MERGE(oxygendependentcoproporphyrinogenoxidase:ENZYME{name: 'oxygen-dependent coproporphyrinogen oxidase'})
MERGE (Gluconobacteroxydans)-[:SYNTHASIZES]->(oxygendependentcoproporphyrinogenoxidase)
MERGE (oxygendependentcoproporphyrinogenoxidase)-[:CATALYZES]->(oxygen)
MERGE(DNAoxidativedemethylaseAlkB:ENZYME{name: 'DNA oxidative demethylase AlkB'})
MERGE (Gluconobacteroxydans)-[:SYNTHASIZES]->(DNAoxidativedemethylaseAlkB)
MERGE (DNAoxidativedemethylaseAlkB)-[:CATALYZES]->(oxygen)
MERGE(glycineoxidaseThiO:ENZYME{name: 'glycine oxidase ThiO'})
MERGE (Gluconobacteroxydans)-[:SYNTHASIZES]->(glycineoxidaseThiO)
MERGE (glycineoxidaseThiO)-[:CATALYZES]->(oxygen)
MERGE(Laspartateoxidase:ENZYME{name: 'L-aspartate oxidase'})
MERGE (Gluconobacteroxydans)-[:SYNTHASIZES]->(Laspartateoxidase)
MERGE (Laspartateoxidase)-[:CATALYZES]->(oxygen)
MERGE(precorrin3Bsynthase:ENZYME{name: 'precorrin-3B synthase'})
MERGE (Gluconobacteroxydans)-[:SYNTHASIZES]->(precorrin3Bsynthase)
MERGE (precorrin3Bsynthase)-[:CATALYZES]->(oxygen)
MERGE(five6dimethylbenzimidazolesynthase:ENZYME{name: '5,6-dimethylbenzimidazole synthase'})
MERGE (Gluconobacteroxydans)-[:SYNTHASIZES]->(five6dimethylbenzimidazolesynthase)
MERGE (five6dimethylbenzimidazolesynthase)-[:CATALYZES]->(oxygen)
MERGE(pyridoxamine5phosphateoxidase:ENZYME{name: 'pyridoxamine 5'-phosphate oxidase'})
MERGE (Gluconobacteroxydans)-[:SYNTHASIZES]->(pyridoxamine5phosphateoxidase)
MERGE (pyridoxamine5phosphateoxidase)-[:CATALYZES]->(oxygen)
MERGE (Gluconobacteroxydans)-[:PRODUCES]->(oxygen)
MERGE(sulfate:CHEMICAL{name: 'sulfate'})
MERGE (Gluconobacteroxydans)-[:CONSUMES]->(sulfate)
MERGE(predictedABCtransporterofsulfate:ENZYME{name: 'predicted ABC transporter of sulfate'})
MERGE (Gluconobacteroxydans)-[:SYNTHASIZES]->(predictedABCtransporterofsulfate)
MERGE (predictedABCtransporterofsulfate)-[:CATALYZES]->(sulfate)
MERGE(adenylylsulfatekinase:ENZYME{name: 'adenylyl-sulfate kinase'})
MERGE (Gluconobacteroxydans)-[:SYNTHASIZES]->(adenylylsulfatekinase)
MERGE (adenylylsulfatekinase)-[:CATALYZES]->(sulfate)
MERGE (Gluconobacteroxydans)-[:PRODUCES]->(sulfate)
MERGE(urea:CHEMICAL{name: 'urea'})
MERGE (Gluconobacteroxydans)-[:PRODUCES]->(urea)
MERGE(ethanol:CHEMICAL{name: 'ethanol'})
MERGE (Gluconobacteroxydans)-[:CONSUMES]->(ethanol)
MERGE(catalase:ENZYME{name: 'catalase'})
MERGE (Gluconobacteroxydans)-[:SYNTHASIZES]->(catalase)
MERGE (catalase)-[:CATALYZES]->(ethanol)
MERGE(zincdependentalcoholdehydrogenase:ENZYME{name: 'zinc-dependent alcohol dehydrogenase'})
MERGE (Gluconobacteroxydans)-[:SYNTHASIZES]->(zincdependentalcoholdehydrogenase)
MERGE (zincdependentalcoholdehydrogenase)-[:CATALYZES]->(ethanol)
MERGE(ShydroxymethylglutathionedehydrogenaseclassIIIalcoholdehydrogenase:ENZYME{name: 'S-(hydroxymethyl)glutathione dehydrogenase/class III alcohol dehydrogenase'})
MERGE (Gluconobacteroxydans)-[:SYNTHASIZES]->(ShydroxymethylglutathionedehydrogenaseclassIIIalcoholdehydrogenase)
MERGE (ShydroxymethylglutathionedehydrogenaseclassIIIalcoholdehydrogenase)-[:CATALYZES]->(ethanol)
MERGE(zincbindingalcoholdehydrogenasefamilyprotein:ENZYME{name: 'zinc-binding alcohol dehydrogenase family protein'})
MERGE (Gluconobacteroxydans)-[:SYNTHASIZES]->(zincbindingalcoholdehydrogenasefamilyprotein)
MERGE (zincbindingalcoholdehydrogenasefamilyprotein)-[:CATALYZES]->(ethanol)
MERGE(alcoholdehydrogenaseAdhP:ENZYME{name: 'alcohol dehydrogenase AdhP'})
MERGE (Gluconobacteroxydans)-[:SYNTHASIZES]->(alcoholdehydrogenaseAdhP)
MERGE (alcoholdehydrogenaseAdhP)-[:CATALYZES]->(ethanol)
MERGE(analcohol:CHEMICAL{name: 'an alcohol'})
MERGE (Gluconobacteroxydans)-[:PRODUCES]->(analcohol)
MERGE(pyrroloquinolinequinone:CHEMICAL{name: 'pyrroloquinoline quinone'})
MERGE (Gluconobacteroxydans)-[:PRODUCES]->(pyrroloquinolinequinone)
MERGE(phosphate:CHEMICAL{name: 'phosphate'})
MERGE (Gluconobacteroxydans)-[:CONSUMES]->(phosphate)
MERGE(inorganicphosphatetransporter:ENZYME{name: 'inorganic phosphate transporter'})
MERGE (Gluconobacteroxydans)-[:SYNTHASIZES]->(inorganicphosphatetransporter)
MERGE (inorganicphosphatetransporter)-[:CATALYZES]->(phosphate)
MERGE(SulPfamilyinorganicaniontransporter:ENZYME{name: 'SulP family inorganic anion transporter'})
MERGE (Gluconobacteroxydans)-[:SYNTHASIZES]->(SulPfamilyinorganicaniontransporter)
MERGE (SulPfamilyinorganicaniontransporter)-[:CATALYZES]->(phosphate)
MERGE(predictedABCtransporterofphosphate:ENZYME{name: 'predicted ABC transporter of phosphate'})
MERGE (Gluconobacteroxydans)-[:SYNTHASIZES]->(predictedABCtransporterofphosphate)
MERGE (predictedABCtransporterofphosphate)-[:CATALYZES]->(phosphate)
MERGE(phosphateABCtransportersubstratebindingproteinPstS:ENZYME{name: 'phosphate ABC transporter substrate-binding protein PstS'})
MERGE (Gluconobacteroxydans)-[:SYNTHASIZES]->(phosphateABCtransportersubstratebindingproteinPstS)
MERGE (phosphateABCtransportersubstratebindingproteinPstS)-[:CATALYZES]->(phosphate)
MERGE(phosphateABCtransporterATPbindingproteinPstB:ENZYME{name: 'phosphate ABC transporter ATP-binding protein PstB'})
MERGE (Gluconobacteroxydans)-[:SYNTHASIZES]->(phosphateABCtransporterATPbindingproteinPstB)
MERGE (phosphateABCtransporterATPbindingproteinPstB)-[:CATALYZES]->(phosphate)
MERGE(typeIglyceraldehyde3phosphatedehydrogenase:ENZYME{name: 'type I glyceraldehyde-3-phosphate dehydrogenase'})
MERGE (Gluconobacteroxydans)-[:SYNTHASIZES]->(typeIglyceraldehyde3phosphatedehydrogenase)
MERGE (typeIglyceraldehyde3phosphatedehydrogenase)-[:CATALYZES]->(phosphate)
MERGE(phosphateacyltransferasePlsX:ENZYME{name: 'phosphate acyltransferase PlsX'})
MERGE (Gluconobacteroxydans)-[:SYNTHASIZES]->(phosphateacyltransferasePlsX)
MERGE (phosphateacyltransferasePlsX)-[:CATALYZES]->(phosphate)
MERGE(Smethyl5thioadenosinephosphorylase:ENZYME{name: 'S-methyl-5'-thioadenosine phosphorylase'})
MERGE (Gluconobacteroxydans)-[:SYNTHASIZES]->(Smethyl5thioadenosinephosphorylase)
MERGE (Smethyl5thioadenosinephosphorylase)-[:CATALYZES]->(phosphate)
MERGE(polyribonucleotidenucleotidyltransferase:ENZYME{name: 'polyribonucleotide nucleotidyltransferase'})
MERGE (Gluconobacteroxydans)-[:SYNTHASIZES]->(polyribonucleotidenucleotidyltransferase)
MERGE (polyribonucleotidenucleotidyltransferase)-[:CATALYZES]->(phosphate)
MERGE(ribonucleasePH:ENZYME{name: 'ribonuclease PH'})
MERGE (Gluconobacteroxydans)-[:SYNTHASIZES]->(ribonucleasePH)
MERGE (ribonucleasePH)-[:CATALYZES]->(phosphate)
MERGE(glutamate5semialdehydedehydrogenase:ENZYME{name: 'glutamate-5-semialdehyde dehydrogenase'})
MERGE (Gluconobacteroxydans)-[:SYNTHASIZES]->(glutamate5semialdehydedehydrogenase)
MERGE (glutamate5semialdehydedehydrogenase)-[:CATALYZES]->(phosphate)
MERGE(aspartatesemialdehydedehydrogenase:ENZYME{name: 'aspartate-semialdehyde dehydrogenase'})
MERGE (Gluconobacteroxydans)-[:SYNTHASIZES]->(aspartatesemialdehydedehydrogenase)
MERGE (aspartatesemialdehydedehydrogenase)-[:CATALYZES]->(phosphate)
MERGE(Nacetylgammaglutamylphosphatereductase:ENZYME{name: 'N-acetyl-gamma-glutamyl-phosphate reductase'})
MERGE (Gluconobacteroxydans)-[:SYNTHASIZES]->(Nacetylgammaglutamylphosphatereductase)
MERGE (Nacetylgammaglutamylphosphatereductase)-[:CATALYZES]->(phosphate)
MERGE (Gluconobacteroxydans)-[:PRODUCES]->(phosphate)
MERGE(Lactococcuslactis:MICROBE{name: 'Lactococcus lactis'})
MERGE(diacetyl:CHEMICAL{name: 'diacetyl'})
MERGE (Lactococcuslactis)-[:PRODUCES]->(diacetyl)
MERGE(Slacticacid:CHEMICAL{name: '(S)-lactic acid'})
MERGE (Lactococcuslactis)-[:PRODUCES]->(Slacticacid)
MERGE(acetaldehyde:CHEMICAL{name: 'acetaldehyde'})
MERGE (Lactococcuslactis)-[:CONSUMES]->(acetaldehyde)
MERGE(bifunctionalacetaldehydeCoAalcoholdehydrogenase:ENZYME{name: 'bifunctional acetaldehyde-CoA/alcohol dehydrogenase'})
MERGE (Lactococcuslactis)-[:SYNTHASIZES]->(bifunctionalacetaldehydeCoAalcoholdehydrogenase)
MERGE (bifunctionalacetaldehydeCoAalcoholdehydrogenase)-[:CATALYZES]->(acetaldehyde)
MERGE (Lactococcuslactis)-[:PRODUCES]->(acetaldehyde)
MERGE(Slactate:CHEMICAL{name: '(S)-lactate'})
MERGE (Lactococcuslactis)-[:CONSUMES]->(Slactate)
MERGE(Llactatedehydrogenase:ENZYME{name: 'L-lactate dehydrogenase'})
MERGE (Lactococcuslactis)-[:SYNTHASIZES]->(Llactatedehydrogenase)
MERGE (Llactatedehydrogenase)-[:CATALYZES]->(Slactate)
MERGE (Lactococcuslactis)-[:PRODUCES]->(Slactate)
MERGE (Lactococcuslactis)-[:CONSUMES]->(ethanol)
MERGE (Lactococcuslactis)-[:SYNTHASIZES]->(zincdependentalcoholdehydrogenase)
MERGE (Lactococcuslactis)-[:SYNTHASIZES]->(ShydroxymethylglutathionedehydrogenaseclassIIIalcoholdehydrogenase)
MERGE (Lactococcuslactis)-[:SYNTHASIZES]->(zincbindingalcoholdehydrogenasefamilyprotein)
MERGE (Lactococcuslactis)-[:SYNTHASIZES]->(alcoholdehydrogenaseAdhP)
MERGE(Smalate:CHEMICAL{name: '(S)-malate'})
MERGE (Lactococcuslactis)-[:CONSUMES]->(Smalate)
MERGE(malolacticenzyme:ENZYME{name: 'malolactic enzyme'})
MERGE (Lactococcuslactis)-[:SYNTHASIZES]->(malolacticenzyme)
MERGE (malolacticenzyme)-[:CATALYZES]->(Smalate)
MERGE(Lactiplantibacillusplantarum:MICROBE{name: 'Lactiplantibacillus plantarum'})
MERGE (Lactiplantibacillusplantarum)-[:CONSUMES]->(Slactate)
MERGE(Llactatepermease:ENZYME{name: 'L-lactate permease'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(Llactatepermease)
MERGE (Llactatepermease)-[:CATALYZES]->(Slactate)
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(Llactatedehydrogenase)
MERGE (Lactiplantibacillusplantarum)-[:PRODUCES]->(Slactate)
MERGE (Lactiplantibacillusplantarum)-[:CONSUMES]->(Smalate)
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(malolacticenzyme)
MERGE(classIIfumaratehydratase:ENZYME{name: 'class II fumarate hydratase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(classIIfumaratehydratase)
MERGE (classIIfumaratehydratase)-[:CATALYZES]->(Smalate)
MERGE(Latilactobacilluscurvatus:MICROBE{name: 'Latilactobacillus curvatus'})
MERGE (Latilactobacilluscurvatus)-[:CONSUMES]->(Slactate)
MERGE (Latilactobacilluscurvatus)-[:SYNTHASIZES]->(Llactatedehydrogenase)
MERGE (Latilactobacilluscurvatus)-[:PRODUCES]->(Slactate)
MERGE (Latilactobacilluscurvatus)-[:CONSUMES]->(Smalate)
MERGE (Latilactobacilluscurvatus)-[:SYNTHASIZES]->(malolacticenzyme)
MERGE (Gluconobacteroxydans)-[:CONSUMES]->(urea)
MERGE(ureacarboxylase:ENZYME{name: 'urea carboxylase'})
MERGE (Gluconobacteroxydans)-[:SYNTHASIZES]->(ureacarboxylase)
MERGE (ureacarboxylase)-[:CATALYZES]->(urea)
MERGE (Lactococcuslactis)-[:CONSUMES]->(Slacticacid)
MERGE(NADPdependentmalicenzyme:ENZYME{name: 'NAD(P)-dependent malic enzyme'})
MERGE (Latilactobacilluscurvatus)-[:SYNTHASIZES]->(NADPdependentmalicenzyme)
MERGE (NADPdependentmalicenzyme)-[:CATALYZES]->(Smalate)
MERGE(ATP:CHEMICAL{name: 'ATP'})
MERGE (Lactiplantibacillusplantarum)-[:CONSUMES]->(ATP)
MERGE(thiolreductantABCexporter:ENZYME{name: 'thiol reductant ABC exporter'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(thiolreductantABCexporter)
MERGE (thiolreductantABCexporter)-[:CATALYZES]->(ATP)
MERGE(oligopeptideABCtransporter:ENZYME{name: 'oligopeptide ABC transporter'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(oligopeptideABCtransporter)
MERGE (oligopeptideABCtransporter)-[:CATALYZES]->(ATP)
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(sevencyanosevendeazaguaninesynthaseQueC)
MERGE (sevencyanosevendeazaguaninesynthaseQueC)-[:CATALYZES]->(ATP)
MERGE(DalanineDalanineligasefamilyprotein:ENZYME{name: 'D-alanine--D-alanine ligase family protein'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(DalanineDalanineligasefamilyprotein)
MERGE (DalanineDalanineligasefamilyprotein)-[:CATALYZES]->(ATP)
MERGE(nicotinatenucleotideadenylyltransferase:ENZYME{name: 'nicotinate-nucleotide adenylyltransferase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(nicotinatenucleotideadenylyltransferase)
MERGE (nicotinatenucleotideadenylyltransferase)-[:CATALYZES]->(ATP)
MERGE(shikimatekinase:ENZYME{name: 'shikimate kinase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(shikimatekinase)
MERGE (shikimatekinase)-[:CATALYZES]->(ATP)
MERGE(chaperoninGroEL:ENZYME{name: 'chaperonin GroEL'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(chaperoninGroEL)
MERGE (chaperoninGroEL)-[:CATALYZES]->(ATP)
MERGE(preproteintranslocasesubunitYajC:ENZYME{name: 'preprotein translocase subunit YajC'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(preproteintranslocasesubunitYajC)
MERGE (preproteintranslocasesubunitYajC)-[:CATALYZES]->(ATP)
MERGE(glyceratekinase:ENZYME{name: 'glycerate kinase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(glyceratekinase)
MERGE (glyceratekinase)-[:CATALYZES]->(ATP)
MERGE(deoxynucleosidekinase:ENZYME{name: 'deoxynucleoside kinase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(deoxynucleosidekinase)
MERGE (deoxynucleosidekinase)-[:CATALYZES]->(ATP)
MERGE(preproteintranslocasesubunitSecY:ENZYME{name: 'preprotein translocase subunit SecY'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(preproteintranslocasesubunitSecY)
MERGE (preproteintranslocasesubunitSecY)-[:CATALYZES]->(ATP)
MERGE(preproteintranslocasesubunitSecG:ENZYME{name: 'preprotein translocase subunit SecG'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(preproteintranslocasesubunitSecG)
MERGE (preproteintranslocasesubunitSecG)-[:CATALYZES]->(ATP)
MERGE(preproteintranslocasesubunitSecA:ENZYME{name: 'preprotein translocase subunit SecA'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(preproteintranslocasesubunitSecA)
MERGE (preproteintranslocasesubunitSecA)-[:CATALYZES]->(ATP)
MERGE(preproteintranslocasesubunitSecE:ENZYME{name: 'preprotein translocase subunit SecE'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(preproteintranslocasesubunitSecE)
MERGE (preproteintranslocasesubunitSecE)-[:CATALYZES]->(ATP)
MERGE(ATPdependentzincmetalloproteaseFtsH:ENZYME{name: 'ATP-dependent zinc metalloprotease FtsH'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(ATPdependentzincmetalloproteaseFtsH)
MERGE (ATPdependentzincmetalloproteaseFtsH)-[:CATALYZES]->(ATP)
MERGE(acetylpropionylmethylcrotonylCoAcarboxylasesubunitalpha:ENZYME{name: 'acetyl/propionyl/methylcrotonyl-CoA carboxylase subunit alpha'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(acetylpropionylmethylcrotonylCoAcarboxylasesubunitalpha)
MERGE (acetylpropionylmethylcrotonylCoAcarboxylasesubunitalpha)-[:CATALYZES]->(ATP)
MERGE(Nacetylglucosaminekinase:ENZYME{name: 'N-acetylglucosamine kinase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(Nacetylglucosaminekinase)
MERGE (Nacetylglucosaminekinase)-[:CATALYZES]->(ATP)
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(AsptRNAAsnGlutRNAGlnamidotransferase)
MERGE (AsptRNAAsnGlutRNAGlnamidotransferase)-[:CATALYZES]->(ATP)
MERGE(typeIIsecretionsystemprotein:ENZYME{name: 'type II secretion system protein'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(typeIIsecretionsystemprotein)
MERGE (typeIIsecretionsystemprotein)-[:CATALYZES]->(ATP)
MERGE(ATPdependentsacrificialsulfurtransferaseLarE:ENZYME{name: 'ATP-dependent sacrificial sulfur transferase LarE'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(ATPdependentsacrificialsulfurtransferaseLarE)
MERGE (ATPdependentsacrificialsulfurtransferaseLarE)-[:CATALYZES]->(ATP)
MERGE(anaerobicribonucleosidetriphosphatereductase:ENZYME{name: 'anaerobic ribonucleoside-triphosphate reductase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(anaerobicribonucleosidetriphosphatereductase)
MERGE (anaerobicribonucleosidetriphosphatereductase)-[:CATALYZES]->(ATP)
MERGE(NADPHhydratedehydratase:ENZYME{name: 'NAD(P)H-hydrate dehydratase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(NADPHhydratedehydratase)
MERGE (NADPHhydratedehydratase)-[:CATALYZES]->(ATP)
MERGE(ABCtransporter:ENZYME{name: 'ABC transporter'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(ABCtransporter)
MERGE (ABCtransporter)-[:CATALYZES]->(ATP)
MERGE(energycouplingfactorABCtransporter:ENZYME{name: 'energy-coupling factor ABC transporter'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(energycouplingfactorABCtransporter)
MERGE (energycouplingfactorABCtransporter)-[:CATALYZES]->(ATP)
MERGE(guanylatekinase:ENZYME{name: 'guanylate kinase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(guanylatekinase)
MERGE (guanylatekinase)-[:CATALYZES]->(ATP)
MERGE(dihydroxyacetonekinase:ENZYME{name: 'dihydroxyacetone kinase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(dihydroxyacetonekinase)
MERGE (dihydroxyacetonekinase)-[:CATALYZES]->(ATP)
MERGE(acetatepropionatefamilykinase:ENZYME{name: 'acetate/propionate family kinase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(acetatepropionatefamilykinase)
MERGE (acetatepropionatefamilykinase)-[:CATALYZES]->(ATP)
MERGE(adenylatekinase:ENZYME{name: 'adenylate kinase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(adenylatekinase)
MERGE (adenylatekinase)-[:CATALYZES]->(ATP)
MERGE(heavymetaltranslocatingPtypeATPase:ENZYME{name: 'heavy metal translocating P-type ATPase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(heavymetaltranslocatingPtypeATPase)
MERGE (heavymetaltranslocatingPtypeATPase)-[:CATALYZES]->(ATP)
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(glutaminehydrolyzingcarbamoylphosphatesynthase)
MERGE (glutaminehydrolyzingcarbamoylphosphatesynthase)-[:CATALYZES]->(ATP)
MERGE(acetylCoAcarboxylase:ENZYME{name: 'acetyl-CoA carboxylase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(acetylCoAcarboxylase)
MERGE (acetylCoAcarboxylase)-[:CATALYZES]->(ATP)
MERGE(acetylCoAcarboxylasecarboxyltransferasesubunitbeta:ENZYME{name: 'acetyl-CoA carboxylase carboxyltransferase subunit beta'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(acetylCoAcarboxylasecarboxyltransferasesubunitbeta)
MERGE (acetylCoAcarboxylasecarboxyltransferasesubunitbeta)-[:CATALYZES]->(ATP)
MERGE(acetylCoAcarboxylasebiotincarboxylcarrierproteinsubunit:ENZYME{name: 'acetyl-CoA carboxylase biotin carboxyl carrier protein subunit'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(acetylCoAcarboxylasebiotincarboxylcarrierproteinsubunit)
MERGE (acetylCoAcarboxylasebiotincarboxylcarrierproteinsubunit)-[:CATALYZES]->(ATP)
MERGE(typeIrestrictionendonucleasesubunitR:ENZYME{name: 'type I restriction endonuclease subunit R'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(typeIrestrictionendonucleasesubunitR)
MERGE (typeIrestrictionendonucleasesubunitR)-[:CATALYZES]->(ATP)
MERGE(galactokinase:ENZYME{name: 'galactokinase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(galactokinase)
MERGE (galactokinase)-[:CATALYZES]->(ATP)
MERGE(phosphoenolpyruvatecarboxykinaseATP:ENZYME{name: 'phosphoenolpyruvate carboxykinase (ATP)'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(phosphoenolpyruvatecarboxykinaseATP)
MERGE (phosphoenolpyruvatecarboxykinaseATP)-[:CATALYZES]->(ATP)
MERGE(twoamino4hydroxy6hydroxymethyldihydropteridinediphosphokinase:ENZYME{name: '2-amino-4-hydroxy-6- hydroxymethyldihydropteridine diphosphokinase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(twoamino4hydroxy6hydroxymethyldihydropteridinediphosphokinase)
MERGE (twoamino4hydroxy6hydroxymethyldihydropteridinediphosphokinase)-[:CATALYZES]->(ATP)
MERGE(tyrosinetRNAligase:ENZYME{name: 'tyrosine--tRNA ligase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(tyrosinetRNAligase)
MERGE (tyrosinetRNAligase)-[:CATALYZES]->(ATP)
MERGE(fivecarboxyaminoimidazoleribonucleotidesynthase:ENZYME{name: '5-(carboxyamino)imidazole ribonucleotide synthase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(fivecarboxyaminoimidazoleribonucleotidesynthase)
MERGE (fivecarboxyaminoimidazoleribonucleotidesynthase)-[:CATALYZES]->(ATP)
MERGE(phosphoribosylaminoimidazolesuccinocarboxamidesynthase:ENZYME{name: 'phosphoribosylaminoimidazolesuccinocarboxamide synthase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(phosphoribosylaminoimidazolesuccinocarboxamidesynthase)
MERGE (phosphoribosylaminoimidazolesuccinocarboxamidesynthase)-[:CATALYZES]->(ATP)
MERGE(phosphoribosylformylglycinamidinesynthase:ENZYME{name: 'phosphoribosylformylglycinamidine synthase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(phosphoribosylformylglycinamidinesynthase)
MERGE (phosphoribosylformylglycinamidinesynthase)-[:CATALYZES]->(ATP)
MERGE(phosphoribosylformylglycinamidinecycloligase:ENZYME{name: 'phosphoribosylformylglycinamidine cyclo-ligase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(phosphoribosylformylglycinamidinecycloligase)
MERGE (phosphoribosylformylglycinamidinecycloligase)-[:CATALYZES]->(ATP)
MERGE(phosphoribosylamineglycineligase:ENZYME{name: 'phosphoribosylamine--glycine ligase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(phosphoribosylamineglycineligase)
MERGE (phosphoribosylamineglycineligase)-[:CATALYZES]->(ATP)
MERGE(lipoateproteinligase:ENZYME{name: 'lipoate--protein ligase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(lipoateproteinligase)
MERGE (lipoateproteinligase)-[:CATALYZES]->(ATP)
MERGE(thymidinekinase:ENZYME{name: 'thymidine kinase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(thymidinekinase)
MERGE (thymidinekinase)-[:CATALYZES]->(ATP)
MERGE(Lthreonylcarbamoyladenylatesynthase:ENZYME{name: 'L-threonylcarbamoyladenylate synthase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(Lthreonylcarbamoyladenylatesynthase)
MERGE (Lthreonylcarbamoyladenylatesynthase)-[:CATALYZES]->(ATP)
MERGE(F0F1ATPsynthase:ENZYME{name: 'F0F1 ATP synthase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(F0F1ATPsynthase)
MERGE (F0F1ATPsynthase)-[:CATALYZES]->(ATP)
MERGE(glutamatecysteineligase:ENZYME{name: 'glutamate--cysteine ligase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(glutamatecysteineligase)
MERGE (glutamatecysteineligase)-[:CATALYZES]->(ATP)
MERGE(bifunctionalglutamatecysteineligaseGshAglutathionesynthetaseGshB:ENZYME{name: 'bifunctional glutamate--cysteine ligase GshA/glutathione synthetase GshB'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(bifunctionalglutamatecysteineligaseGshAglutathionesynthetaseGshB)
MERGE (bifunctionalglutamatecysteineligaseGshAglutathionesynthetaseGshB)-[:CATALYZES]->(ATP)
MERGE(tRNAuracil4sulfurtransferaseThiI:ENZYME{name: 'tRNA uracil 4-sulfurtransferase ThiI'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(tRNAuracil4sulfurtransferaseThiI)
MERGE (tRNAuracil4sulfurtransferaseThiI)-[:CATALYZES]->(ATP)
MERGE(valinetRNAligase:ENZYME{name: 'valine--tRNA ligase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(valinetRNAligase)
MERGE (valinetRNAligase)-[:CATALYZES]->(ATP)
MERGE(alaninetRNAligase:ENZYME{name: 'alanine--tRNA ligase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(alaninetRNAligase)
MERGE (alaninetRNAligase)-[:CATALYZES]->(ATP)
MERGE(ribokinase:ENZYME{name: 'ribokinase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(ribokinase)
MERGE (ribokinase)-[:CATALYZES]->(ATP)
MERGE(NADkinase:ENZYME{name: 'NAD kinase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(NADkinase)
MERGE (NADkinase)-[:CATALYZES]->(ATP)
MERGE(UDPNacetylmuramoylLalanineDglutamateligase:ENZYME{name: 'UDP-N-acetylmuramoyl-L-alanine--D-glutamate ligase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(UDPNacetylmuramoylLalanineDglutamateligase)
MERGE (UDPNacetylmuramoylLalanineDglutamateligase)-[:CATALYZES]->(ATP)
MERGE(isoleucinetRNAligase:ENZYME{name: 'isoleucine--tRNA ligase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(isoleucinetRNAligase)
MERGE (isoleucinetRNAligase)-[:CATALYZES]->(ATP)
MERGE(tRNA2thiouridine34synthaseMnmA:ENZYME{name: 'tRNA 2-thiouridine(34) synthase MnmA'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(tRNA2thiouridine34synthaseMnmA)
MERGE (tRNA2thiouridine34synthaseMnmA)-[:CATALYZES]->(ATP)
MERGE(pyruvatecarboxylase:ENZYME{name: 'pyruvate carboxylase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(pyruvatecarboxylase)
MERGE (pyruvatecarboxylase)-[:CATALYZES]->(ATP)
MERGE(pantetheinephosphateadenylyltransferase:ENZYME{name: 'pantetheine-phosphate adenylyltransferase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(pantetheinephosphateadenylyltransferase)
MERGE (pantetheinephosphateadenylyltransferase)-[:CATALYZES]->(ATP)
MERGE(CpsDCapBfamilytyrosineproteinkinase:ENZYME{name: 'CpsD/CapB family tyrosine-protein kinase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(CpsDCapBfamilytyrosineproteinkinase)
MERGE (CpsDCapBfamilytyrosineproteinkinase)-[:CATALYZES]->(ATP)
MERGE(onephosphofructokinase:ENZYME{name: '1-phosphofructokinase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(onephosphofructokinase)
MERGE (onephosphofructokinase)-[:CATALYZES]->(ATP)
MERGE(UMPkinase:ENZYME{name: 'UMP kinase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(UMPkinase)
MERGE (UMPkinase)-[:CATALYZES]->(ATP)
MERGE(prolinetRNAligase:ENZYME{name: 'proline--tRNA ligase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(prolinetRNAligase)
MERGE (prolinetRNAligase)-[:CATALYZES]->(ATP)
MERGE(riboflavinbiosynthesisproteinRibF:ENZYME{name: 'riboflavin biosynthesis protein RibF'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(riboflavinbiosynthesisproteinRibF)
MERGE (riboflavinbiosynthesisproteinRibF)-[:CATALYZES]->(ATP)
MERGE(bifunctionalpppGppsynthetaseguanosine35bisdiphosphate3pyrophosphohydrolase:ENZYME{name: 'bifunctional (p)ppGpp synthetase/guanosine-3',5'-bis(diphosphate) 3'-pyrophosphohydrolase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(bifunctionalpppGppsynthetaseguanosine35bisdiphosphate3pyrophosphohydrolase)
MERGE (bifunctionalpppGppsynthetaseguanosine35bisdiphosphate3pyrophosphohydrolase)-[:CATALYZES]->(ATP)
MERGE(histidinetRNAligase:ENZYME{name: 'histidine--tRNA ligase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(histidinetRNAligase)
MERGE (histidinetRNAligase)-[:CATALYZES]->(ATP)
MERGE(aspartatetRNAligase:ENZYME{name: 'aspartate--tRNA ligase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(aspartatetRNAligase)
MERGE (aspartatetRNAligase)-[:CATALYZES]->(ATP)
MERGE(glycinetRNAligase:ENZYME{name: 'glycine--tRNA ligase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(glycinetRNAligase)
MERGE (glycinetRNAligase)-[:CATALYZES]->(ATP)
MERGE(phosphoenolpyruvatesynthase:ENZYME{name: 'phosphoenolpyruvate synthase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(phosphoenolpyruvatesynthase)
MERGE (phosphoenolpyruvatesynthase)-[:CATALYZES]->(ATP)
MERGE(sixphosphofructokinase:ENZYME{name: '6-phosphofructokinase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(sixphosphofructokinase)
MERGE (sixphosphofructokinase)-[:CATALYZES]->(ATP)
MERGE(pyruvatekinase:ENZYME{name: 'pyruvate kinase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(pyruvatekinase)
MERGE (pyruvatekinase)-[:CATALYZES]->(ATP)
MERGE(dCMPkinase:ENZYME{name: '(d)CMP kinase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(dCMPkinase)
MERGE (dCMPkinase)-[:CATALYZES]->(ATP)
MERGE(CCAtRNAnucleotidyltransferase:ENZYME{name: 'CCA tRNA nucleotidyltransferase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(CCAtRNAnucleotidyltransferase)
MERGE (CCAtRNAnucleotidyltransferase)-[:CATALYZES]->(ATP)
MERGE(ATPdependentproteaseATPase:ENZYME{name: 'ATP-dependent protease ATPase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(ATPdependentproteaseATPase)
MERGE (ATPdependentproteaseATPase)-[:CATALYZES]->(ATP)
MERGE(formatetetrahydrofolateligase:ENZYME{name: 'formate--tetrahydrofolate ligase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(formatetetrahydrofolateligase)
MERGE (formatetetrahydrofolateligase)-[:CATALYZES]->(ATP)
MERGE(methionineABCtransporter:ENZYME{name: 'methionine ABC transporter'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(methionineABCtransporter)
MERGE (methionineABCtransporter)-[:CATALYZES]->(ATP)
MERGE(mevalonatekinase:ENZYME{name: 'mevalonate kinase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(mevalonatekinase)
MERGE (mevalonatekinase)-[:CATALYZES]->(ATP)
MERGE(diphosphomevalonatedecarboxylase:ENZYME{name: 'diphosphomevalonate decarboxylase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(diphosphomevalonatedecarboxylase)
MERGE (diphosphomevalonatedecarboxylase)-[:CATALYZES]->(ATP)
MERGE(phosphomevalonatekinase:ENZYME{name: 'phosphomevalonate kinase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(phosphomevalonatekinase)
MERGE (phosphomevalonatekinase)-[:CATALYZES]->(ATP)
MERGE(thiaminediphosphokinase:ENZYME{name: 'thiamine diphosphokinase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(thiaminediphosphokinase)
MERGE (thiaminediphosphokinase)-[:CATALYZES]->(ATP)
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(typeIglutamateammonialigase)
MERGE (typeIglutamateammonialigase)-[:CATALYZES]->(ATP)
MERGE(ROKfamilyglucokinase:ENZYME{name: 'ROK family glucokinase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(ROKfamilyglucokinase)
MERGE (ROKfamilyglucokinase)-[:CATALYZES]->(ATP)
MERGE(fiveformyltetrahydrofolatecycloligase:ENZYME{name: '5-formyltetrahydrofolate cyclo-ligase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(fiveformyltetrahydrofolatecycloligase)
MERGE (fiveformyltetrahydrofolatecycloligase)-[:CATALYZES]->(ATP)
MERGE(uridinekinase:ENZYME{name: 'uridine kinase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(uridinekinase)
MERGE (uridinekinase)-[:CATALYZES]->(ATP)
MERGE(phenylalaninetRNAligase:ENZYME{name: 'phenylalanine--tRNA ligase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(phenylalaninetRNAligase)
MERGE (phenylalaninetRNAligase)-[:CATALYZES]->(ATP)
MERGE(threoninetRNAligase:ENZYME{name: 'threonine--tRNA ligase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(threoninetRNAligase)
MERGE (threoninetRNAligase)-[:CATALYZES]->(ATP)
MERGE(dephosphoCoAkinase:ENZYME{name: 'dephospho-CoA kinase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(dephosphoCoAkinase)
MERGE (dephosphoCoAkinase)-[:CATALYZES]->(ATP)
MERGE(UDPNacetylmuramateLalanineligase:ENZYME{name: 'UDP-N-acetylmuramate--L-alanine ligase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(UDPNacetylmuramateLalanineligase)
MERGE (UDPNacetylmuramateLalanineligase)-[:CATALYZES]->(ATP)
MERGE(Dalaninepolyphosphoribitolligase:ENZYME{name: 'D-alanine--poly(phosphoribitol) ligase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(Dalaninepolyphosphoribitolligase)
MERGE (Dalaninepolyphosphoribitolligase)-[:CATALYZES]->(ATP)
MERGE(DalaninepolyphosphoribitolligasesubunitDltC:ENZYME{name: 'D-alanine--poly(phosphoribitol) ligase subunit DltC'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(DalaninepolyphosphoribitolligasesubunitDltC)
MERGE (DalaninepolyphosphoribitolligasesubunitDltC)-[:CATALYZES]->(ATP)
MERGE(argininetRNAligase:ENZYME{name: 'arginine--tRNA ligase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(argininetRNAligase)
MERGE (argininetRNAligase)-[:CATALYZES]->(ATP)
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(adenylylsulfatekinase)
MERGE (adenylylsulfatekinase)-[:CATALYZES]->(ATP)
MERGE(sulfateadenylyltransferase:ENZYME{name: 'sulfate adenylyltransferase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(sulfateadenylyltransferase)
MERGE (sulfateadenylyltransferase)-[:CATALYZES]->(ATP)
MERGE(leucinetRNAligase:ENZYME{name: 'leucine--tRNA ligase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(leucinetRNAligase)
MERGE (leucinetRNAligase)-[:CATALYZES]->(ATP)
MERGE(methionineadenosyltransferase:ENZYME{name: 'methionine adenosyltransferase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(methionineadenosyltransferase)
MERGE (methionineadenosyltransferase)-[:CATALYZES]->(ATP)
MERGE(gluconokinase:ENZYME{name: 'gluconokinase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(gluconokinase)
MERGE (gluconokinase)-[:CATALYZES]->(ATP)
MERGE(diacylglycerolkinase:ENZYME{name: 'diacylglycerol kinase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(diacylglycerolkinase)
MERGE (diacylglycerolkinase)-[:CATALYZES]->(ATP)
MERGE([citratepro3Slyase]ligase:ENZYME{name: '[citrate (pro-3S)-lyase] ligase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->([citratepro3Slyase]ligase)
MERGE ([citratepro3Slyase]ligase)-[:CATALYZES]->(ATP)
MERGE(triphosphoribosyldephosphoCoAsynthase:ENZYME{name: 'triphosphoribosyl-dephospho-CoA synthase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(triphosphoribosyldephosphoCoAsynthase)
MERGE (triphosphoribosyldephosphoCoAsynthase)-[:CATALYZES]->(ATP)
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(asparaginesynthaseglutaminehydrolyzing)
MERGE (asparaginesynthaseglutaminehydrolyzing)-[:CATALYZES]->(ATP)
MERGE(aspartatekinase:ENZYME{name: 'aspartate kinase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(aspartatekinase)
MERGE (aspartatekinase)-[:CATALYZES]->(ATP)
MERGE(Murligasefamilyprotein:ENZYME{name: 'Mur ligase family protein'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(Murligasefamilyprotein)
MERGE (Murligasefamilyprotein)-[:CATALYZES]->(ATP)
MERGE(UDPNacetylmuramoylLalanylDglutamate26diaminopimelateligase:ENZYME{name: 'UDP-N-acetylmuramoyl-L-alanyl-D-glutamate--2, 6-diaminopimelate ligase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(UDPNacetylmuramoylLalanylDglutamate26diaminopimelateligase)
MERGE (UDPNacetylmuramoylLalanylDglutamate26diaminopimelateligase)-[:CATALYZES]->(ATP)
MERGE(asparaginetRNAligase:ENZYME{name: 'asparagine--tRNA ligase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(asparaginetRNAligase)
MERGE (asparaginetRNAligase)-[:CATALYZES]->(ATP)
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(glutaminehydrolyzingGMPsynthase)
MERGE (glutaminehydrolyzingGMPsynthase)-[:CATALYZES]->(ATP)
MERGE(typeIpantothenatekinase:ENZYME{name: 'type I pantothenate kinase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(typeIpantothenatekinase)
MERGE (typeIpantothenatekinase)-[:CATALYZES]->(ATP)
MERGE(RNAdegradosomepolyphosphatekinase:ENZYME{name: 'RNA degradosome polyphosphate kinase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(RNAdegradosomepolyphosphatekinase)
MERGE (RNAdegradosomepolyphosphatekinase)-[:CATALYZES]->(ATP)
MERGE(diadenylatecyclaseCdaA:ENZYME{name: 'diadenylate cyclase CdaA'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(diadenylatecyclaseCdaA)
MERGE (diadenylatecyclaseCdaA)-[:CATALYZES]->(ATP)
MERGE(phosphoglyceratekinase:ENZYME{name: 'phosphoglycerate kinase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(phosphoglyceratekinase)
MERGE (phosphoglyceratekinase)-[:CATALYZES]->(ATP)
MERGE(ATPdependentClpproteaseATPbindingsubunitClpX:ENZYME{name: 'ATP-dependent Clp protease ATP-binding subunit ClpX'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(ATPdependentClpproteaseATPbindingsubunitClpX)
MERGE (ATPdependentClpproteaseATPbindingsubunitClpX)-[:CATALYZES]->(ATP)
MERGE(ATPdependentClpendopeptidaseproteolyticsubunitClpP:ENZYME{name: 'ATP-dependent Clp endopeptidase proteolytic subunit ClpP'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(ATPdependentClpendopeptidaseproteolyticsubunitClpP)
MERGE (ATPdependentClpendopeptidaseproteolyticsubunitClpP)-[:CATALYZES]->(ATP)
MERGE(argininosuccinatesynthase:ENZYME{name: 'argininosuccinate synthase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(argininosuccinatesynthase)
MERGE (argininosuccinatesynthase)-[:CATALYZES]->(ATP)
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(phosphateABCtransporterATPbindingproteinPstB)
MERGE (phosphateABCtransporterATPbindingproteinPstB)-[:CATALYZES]->(ATP)
MERGE(phosphateABCtransporter:ENZYME{name: 'phosphate ABC transporter'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(phosphateABCtransporter)
MERGE (phosphateABCtransporter)-[:CATALYZES]->(ATP)
MERGE(phosphonateABCtransporter:ENZYME{name: 'phosphonate ABC transporter'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(phosphonateABCtransporter)
MERGE (phosphonateABCtransporter)-[:CATALYZES]->(ATP)
MERGE(dTMPkinase:ENZYME{name: 'dTMP kinase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(dTMPkinase)
MERGE (dTMPkinase)-[:CATALYZES]->(ATP)
MERGE(cysteinetRNAligase:ENZYME{name: 'cysteine--tRNA ligase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(cysteinetRNAligase)
MERGE (cysteinetRNAligase)-[:CATALYZES]->(ATP)
MERGE(glutamatetRNAligase:ENZYME{name: 'glutamate--tRNA ligase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(glutamatetRNAligase)
MERGE (glutamatetRNAligase)-[:CATALYZES]->(ATP)
MERGE(homoserinekinase:ENZYME{name: 'homoserine kinase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(homoserinekinase)
MERGE (homoserinekinase)-[:CATALYZES]->(ATP)
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(NADsynthase)
MERGE (NADsynthase)-[:CATALYZES]->(ATP)
MERGE(nicotinatephosphoribosyltransferase:ENZYME{name: 'nicotinate phosphoribosyltransferase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(nicotinatephosphoribosyltransferase)
MERGE (nicotinatephosphoribosyltransferase)-[:CATALYZES]->(ATP)
MERGE(lysinetRNAligase:ENZYME{name: 'lysine--tRNA ligase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(lysinetRNAligase)
MERGE (lysinetRNAligase)-[:CATALYZES]->(ATP)
MERGE(tRNAlysidine34synthetaseTilS:ENZYME{name: 'tRNA lysidine(34) synthetase TilS'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(tRNAlysidine34synthetaseTilS)
MERGE (tRNAlysidine34synthetaseTilS)-[:CATALYZES]->(ATP)
MERGE(acetylglutamatekinase:ENZYME{name: 'acetylglutamate kinase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(acetylglutamatekinase)
MERGE (acetylglutamatekinase)-[:CATALYZES]->(ATP)
MERGE(carbamoylphosphatesynthasesmallsubunit:ENZYME{name: 'carbamoyl phosphate synthase small subunit'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(carbamoylphosphatesynthasesmallsubunit)
MERGE (carbamoylphosphatesynthasesmallsubunit)-[:CATALYZES]->(ATP)
MERGE(carbamoylphosphatesynthase:ENZYME{name: 'carbamoyl-phosphate synthase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(carbamoylphosphatesynthase)
MERGE (carbamoylphosphatesynthase)-[:CATALYZES]->(ATP)
MERGE(ABCtransporterATPbindingprotein:ENZYME{name: 'ABC transporter ATP-binding protein'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(ABCtransporterATPbindingprotein)
MERGE (ABCtransporterATPbindingprotein)-[:CATALYZES]->(ATP)
MERGE(UDPNacetylmuramoyltripeptideDalanylDalanineligase:ENZYME{name: 'UDP-N-acetylmuramoyl-tripeptide--D-alanyl-D- alanine ligase'})
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(UDPNacetylmuramoyltripeptideDalanylDalanineligase)
MERGE (UDPNacetylmuramoyltripeptideDalanylDalanineligase)-[:CATALYZES]->(ATP)
MERGE (Lactiplantibacillusplantarum)-[:SYNTHASIZES]->(CTPsynthase)
MERGE (CTPsynthase)-[:CATALYZES]->(ATP)
MERGE (Lactiplantibacillusplantarum)-[:PRODUCES]->(ATP)
