MERGE (Lthermotolerans:MICROBE_NAME{name:'L. thermotolerans'})
MERGE (glycerol:COMPOUND{name:'glycerol'})
MERGE (Lthermotolerans)-[:PRODUCES]->(glycerol)
MERGE (twophenylethanol:COMPOUND{name:'2-phenyl ethanol'})
MERGE (Lthermotolerans)-[:PRODUCES]->(twophenylethanol)
MERGE (Scerevisiae:MICROBE_NAME{name:'S. cerevisiae'})
MERGE (Scerevisiae)-[:PRODUCES]->(glycerol)
MERGE (Scerevisiae)-[:PRODUCES]->(twophenylethanol)
MERGE (Candidautilis:MICROBE_NAME{name:'Candida utilis'})
MERGE (xylose:COMPOUND{name:'xylose'})
MERGE (Candidautilis)-[:CONSUMES]->(xylose)
MERGE (ethanol:COMPOUND{name:'ethanol'})
MERGE (aceticacid:COMPOUND{name:'acetic acid'})
MERGE (ethanol)-[:BECOMES]->(aceticacid)
MERGE (glucose:COMPOUND{name:'glucose'})
MERGE (gluconicacid:COMPOUND{name:'gluconic acid'})
MERGE (glucose)-[:BECOMES]->(gluconicacid)
MERGE (Czemplinina:MICROBE_NAME{name:'C. zemplinina'})
MERGE (fructose:COMPOUND{name:'fructose'})
MERGE (Czemplinina)-[:CONSUMES]->(fructose)
MERGE (Lpbplantarum:MICROBE_NAME{name:'Lpb. plantarum'})
MERGE (pyrazines:COMPOUND{name:'pyrazines'})
MERGE (Lpbplantarum)-[:PRODUCES]->(pyrazines)
MERGE (Bsubtilisvarnatto:MICROBE_NAME{name:'B. subtilis var. natto'})
MERGE (Bsubtilisvarnatto)-[:PRODUCES]->(pyrazines)
MERGE (twofurfurylmethanol:COMPOUND{name:'2-furfuryl methanol'})
MERGE (hexanoicacid:COMPOUND{name:'hexanoic acid'})
MERGE (benzoicacid:COMPOUND{name:'benzoic acid'})
MERGE (ketobutyricacid:COMPOUND{name:'ketobutyric acid'})
MERGE (riboflavin:COMPOUND{name:'riboflavin'})
MERGE (tricarboxylicacid:COMPOUND{name:'tricarboxylic acid'})
MERGE (riboflavin)-[:BECOMES]->(tricarboxylicacid)
MERGE (pyridoxin:COMPOUND{name:'pyridoxin'})
MERGE (pyridoxin)-[:BECOMES]->(tricarboxylicacid)
MERGE (glucose)-[:BECOMES]->(ethanol)
MERGE (fructose)-[:BECOMES]->(ethanol)
MERGE (citricacid:COMPOUND{name:'citric acid'})
MERGE (diacetyl:COMPOUND{name:'diacetyl'})
MERGE (citricacid)-[:BECOMES]->(diacetyl)
MERGE (acetoin:COMPOUND{name:'acetoin'})
MERGE (citricacid)-[:BECOMES]->(acetoin)
MERGE (two3butanediol:COMPOUND{name:'2,3-butanediol'})
MERGE (citricacid)-[:BECOMES]->(two3butanediol)
MERGE (phenylalanine:COMPOUND{name:'phenylalanine'})
MERGE (phenylacetaldehyde:COMPOUND{name:'phenylacetaldehyde'})
MERGE (phenylalanine)-[:BECOMES]->(phenylacetaldehyde)
MERGE (sweetsorghum:SUBSTRATE{name:'sweet sorghum'})
MERGE (bioethanol:COMPOUND{name:'bioethanol'})
MERGE (sweetsorghum)-[:BECOMES]->(bioethanol)
MERGE (orangewaste:SUBSTRATE{name:'orange waste'})
MERGE (lacticacid:COMPOUND{name:'lactic acid'})
MERGE (orangewaste)-[:BECOMES]->(lacticacid)
MERGE (propanoicacid:COMPOUND{name:'propanoic acid'})
MERGE (orangewaste)-[:BECOMES]->(propanoicacid)
MERGE (Acetobacterspp:MICROBE_NAME{name:'Acetobacter spp'})
MERGE (Acetobacterspp)-[:CONSUMES]->(glucose)
MERGE (Acetobacter:MICROBE_NAME{name:'Acetobacter'})
MERGE (Acetobacter)-[:CONSUMES]->(ethanol)
MERGE (Acetobacter)-[:PRODUCES]->(aceticacid)
MERGE (Acetobacter)-[:PRODUCES]->(gluconicacid)
MERGE (sorbitol:COMPOUND{name:'sorbitol'})
MERGE (ascorbicacid:COMPOUND{name:'ascorbic acid'})
MERGE (sorbitol)-[:BECOMES]->(ascorbicacid)
MERGE (Gluconobacteroxydans:MICROBE_NAME{name:'Gluconobacter oxydans'})
MERGE (Gluconobacteroxydans)-[:CONSUMES]->(sorbitol)
MERGE (sorbose:COMPOUND{name:'sorbose'})
MERGE (Gluconobacteroxydans)-[:PRODUCES]->(sorbose)
MERGE (sorbitol)-[:BECOMES]->(sorbose)
MERGE (gulonicacid:COMPOUND{name:'gulonic acid'})
MERGE (methylgluconate:COMPOUND{name:'methyl gluconate'})
MERGE (gulonicacid)-[:BECOMES]->(methylgluconate)
MERGE (Enterococcusfaecium:MICROBE_NAME{name:'Enterococcus faecium'})
MERGE (thiamine:COMPOUND{name:'thiamine'})
MERGE (Enterococcusfaecium)-[:CONSUMES]->(thiamine)
MERGE (Enterococcusfaecium)-[:CONSUMES]->(riboflavin)
MERGE (niacin:COMPOUND{name:'niacin'})
MERGE (Enterococcusfaecium)-[:CONSUMES]->(niacin)
MERGE (isoflavones:COMPOUND{name:'isoflavones'})
MERGE (aglycone:COMPOUND{name:'aglycone'})
MERGE (isoflavones)-[:BECOMES]->(aglycone)
MERGE (Acetoine:COMPOUND{name:'Acetoine'})
MERGE (Acetoine)-[:BECOMES]->(diacetyl)
MERGE (peptides:COMPOUND{name:'peptides'})
MERGE (ammonia:COMPOUND{name:'ammonia'})
MERGE (peptides)-[:BECOMES]->(ammonia)
MERGE (Scerevisiae)-[:PRODUCES]->(ethanol)
MERGE (Scerevisiae)-[:PRODUCES]->(lacticacid)
MERGE (lactose:COMPOUND{name:'lactose'})
MERGE (lactose)-[:BECOMES]->(lacticacid)
MERGE (lactose)-[:BECOMES]->(ethanol)
MERGE (lactulose:COMPOUND{name:'lactulose'})
MERGE (lactose)-[:BECOMES]->(lactulose)
MERGE (Limosilactobacillusreuteri:MICROBE_NAME{name:'Limosilactobacillus reuteri'})
MERGE (reuterin:COMPOUND{name:'reuterin'})
MERGE (Limosilactobacillusreuteri)-[:PRODUCES]->(reuterin)
MERGE (Aaceti:MICROBE_NAME{name:'A. aceti'})
MERGE (Aaceti)-[:CONSUMES]->(ethanol)
MERGE (Aaceti)-[:CONSUMES]->(glycerol)
MERGE (Aaceti)-[:CONSUMES]->(glucose)
MERGE (malicacid:COMPOUND{name:'malic acid'})
MERGE (malicacid)-[:BECOMES]->(lacticacid)
MERGE (sucrose:COMPOUND{name:'sucrose'})
MERGE (sucrose)-[:BECOMES]->(fructose)
MERGE (sucrose)-[:BECOMES]->(glucose)
MERGE (onenonanol:COMPOUND{name:'1-nonanol'})
MERGE (twodecanone:COMPOUND{name:'2-decanone'})
MERGE (twoundecanone:COMPOUND{name:'2-undecanone'})
MERGE (phenylaldehyde:COMPOUND{name:'phenyl aldehyde'})
MERGE (benzylalcohol:COMPOUND{name:'benzyl alcohol'})
MERGE (threonine:COMPOUND{name:'threonine'})
MERGE (aminoacetone:COMPOUND{name:'aminoacetone'})
MERGE (threonine)-[:BECOMES]->(aminoacetone)
MERGE (aminoacetone)-[:BECOMES]->(pyrazines)
MERGE (pentanedione:COMPOUND{name:'pentanedione'})
MERGE (twoaminopentan3one:COMPOUND{name:'2-aminopentan-3-one'})
MERGE (pentanedione)-[:BECOMES]->(twoaminopentan3one)
MERGE (pyrazine:COMPOUND{name:'pyrazine'})
MERGE (twoaminopentan3one)-[:BECOMES]->(pyrazine)
MERGE (Aminoacetone:COMPOUND{name:'Aminoacetone'})
MERGE (pyruvate:COMPOUND{name:'pyruvate'})
MERGE (Aminoacetone)-[:BECOMES]->(pyruvate)
MERGE (pyruvate)-[:BECOMES]->(acetoin)
MERGE (Bacillussp:MICROBE_NAME{name:'Bacillus sp.'})
MERGE (aminocaproicacid:COMPOUND{name:'aminocaproic acid'})
MERGE (Bacillussp)-[:PRODUCES]->(aminocaproicacid)
MERGE (Alcaligeneslactamolyticus:MICROBE_NAME{name:'Alcaligenes lactamolyticus'})
MERGE (caproicacid:COMPOUND{name:'caproic acid'})
MERGE (Alcaligeneslactamolyticus)-[:PRODUCES]->(caproicacid)
MERGE (Achromobactersp:MICROBE_NAME{name:'Achromobacter sp.'})
MERGE (Achromobactersp)-[:PRODUCES]->(caproicacid)
MERGE (amine:COMPOUND{name:'amine'})
MERGE (amine)-[:BECOMES]->(ammonia)
MERGE (Oenococcusoeni:MICROBE_NAME{name:'Oenococcus oeni'})
MERGE (Acetobacteraceti:MICROBE_NAME{name:'Acetobacter aceti'})
MERGE (Gluconacetobacterhansenii:MICROBE_NAME{name:'Gluconacetobacter hansenii'})
MERGE (Gluconacetobacterhansenii)-[:PRODUCES]->(aceticacid)
MERGE (Candidatropicalis:MICROBE_NAME{name:'Candida tropicalis'})
MERGE (Bsubtilisvarnatto)-[:PRODUCES]->(pyrazine)
MERGE (peptide:COMPOUND{name:'peptide'})
MERGE (Bsubtilisvarnatto)-[:CONSUMES]->(peptide)
MERGE (Lpbplantarum)-[:CONSUMES]->(peptide)
MERGE (Bsubtilisvarnatto)-[:PRODUCES]->(ammonia)
MERGE (Methylomonasmethylovara:MICROBE_NAME{name:'Methylomonas methylovara'})
MERGE (glutamicacid:COMPOUND{name:'glutamic acid'})
MERGE (Methylomonasmethylovara)-[:PRODUCES]->(glutamicacid)
MERGE (Aspergillusniger:MICROBE_NAME{name:'Aspergillus niger'})
MERGE (Aspergillusniger)-[:PRODUCES]->(citricacid)
MERGE (Candidalipolytica:MICROBE_NAME{name:'Candida lipolytica'})
MERGE (Citricacid:COMPOUND{name:'Citric acid'})
MERGE (Candidalipolytica)-[:PRODUCES]->(Citricacid)
